/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author migu_
 */
public class frmMain extends javax.swing.JFrame {
    
    String[][] sala_cine = new String[3][5]; // sala de cine con 5 asientos en cada fila
    int filas_llenas; // contador de filas que se van llenando
    int asientos_ocupados = -1; // contador de posiciones para los asientos de una fila
    Monitor vigilante;
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        for (int i=0; i<3; i++) {
            for (int j=0; j<5; j++)
                sala_cine[i][j] = "Vacío";
        }
    }
    
    public class Cliente extends Thread {
        String nombre;
        String asiento_obtenido;
        float dinero;

        public Cliente(char letra) {
            nombre = "Cliente " + letra;
            this.dinero = (float) (Math.round((((Math.random()* 50)+50))*100))/100;
        }
        
        @Override
        public void run() {
            System.out.println("Proceso " + this.nombre + " iniciado. Tengo Q " + this.dinero);
            // Antes de escoger asiento debe comprar lo que pueda con el dinero que tenga
            // La entrada cuesta Q 48, los poporopos Q 30 y los dulces Q 5
            String compra="";
            this.dinero =this.dinero- 48;
            if(this.dinero>30)
            {
                compra = ", palomitas,";
                this.dinero = this.dinero - 30;
            }
            if(this.dinero>5)
            {
               // int dulces = (int)this.dinero %5;
                compra =  ", dulce";
                this.dinero = this.dinero - 5;
            }
            System.out.println("Ha decidido comprar boleto" + compra);
            
            //Region Critica
            vigilante.Ingresar(this.nombre);
            String fila = switch (filas_llenas) {
                case 0 -> "A";
                case 1 -> "B";
                default -> "C";
            };
            asientos_ocupados++;
            if(asientos_ocupados==5)
            {
             filas_llenas++;
            }
            asientos_ocupados=asientos_ocupados%5 ;
            this.asiento_obtenido = "Fila " + fila + " Asiento " + String.valueOf(asientos_ocupados+1);
            sala_cine[filas_llenas][asientos_ocupados] = vigilante.Retirar();
            //Fin Region Critica
            
            
            // el cliente debe indicarle al portero que asiento tiene
            // también debe mostrar cuanto le quedo de dinero para el próximo estreno
            String result= this.nombre + " Asiento: " + this.asiento_obtenido +  " Dinero Restante:" + (Math.round(this.dinero*100))/100;
            System.out.println(result);
            System.out.println(this.nombre + " finalizado con status: 0");
        }
    }

   class Monitor
    {
        private String fila_caja[] = new String[15];
        private int inf=0, sup=0; 
          
        public synchronized void Ingresar(String cliente){
            fila_caja[sup]=cliente; // inserta un elemento en el búfer
            sup++; // direccion en la que se colocara el siguiente elemento
        }
        
        public synchronized String Retirar(){
            String cliente="";
             cliente=fila_caja[inf]; // obtiene un elemento del búfer
             inf ++; // espacio del siguiente elemento que se obtendra
             return cliente;
        }

}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnVerAsientos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("2a Evaluación Parcial");

        btnBuscar.setText("Buscar boletos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVerAsientos.setText("Ver asientos");
        btnVerAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAsientosActionPerformed(evt);
            }
        });

        jLabel2.setText("Función: Dr. Strange in the multiverse of madness");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(btnBuscar)
                            .addGap(80, 80, 80)
                            .addComponent(btnVerAsientos))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVerAsientos))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 5; j++) {
                sala_cine[i][j] = "Vacío";
            }
        }
        asientos_ocupados = -1;
        filas_llenas=0;
        vigilante = new Monitor();
        Cliente c;
        char letra = 'A';
        for (int i=0; i<15; i++){
            c = new Cliente(letra);
            c.start();
            letra++;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsientosActionPerformed
        System.out.println("Asientos de la sala:");
        for (int i=0; i<3; i++) {
            String fila = "";
            for (int j=0; j<5; j++) {
                fila += "[" + sala_cine[i][j] + "] ";
            }
            System.out.println(fila);
        }
    }//GEN-LAST:event_btnVerAsientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVerAsientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
